### ISSUE TITLE
Wrong parameter name

### ISSUE THREAD

**Issue by MartinMikita** [cryptlex/lexactivator-c#6]
https://github.com/cryptlex/lexactivator-c/blob/cfce949c8bf09661412e3001e49ad18a189eaf45/examples/LexActivator.h#L122

The name `flags` assume, you can use binary operation - `SetProductId("paste_product_id", LA_IN_MEMORY | LA_USER);`)

**Comment by adnan-kamili** [comment]
Thanks @MartinMikita for reporting the issue. It has been fixed.
